### PR TITLE
Add CSS classes to change cursors to reflect locked layout 

### PR DESCRIPTION
**Pull request by adityatoshniwal**
Add class to wcDocker container based on lock layout level when lock layout is called.
The classes are:
1) NONE : wcLockNone
2) PREVENT_DOCKING : wcLockPreventDocking
3) FULL: wcLockFull

Kindly review.

### CODE REVIEW

**Review by dpage — COMMENTED** [review]
This pull request seems to add a huge amount of new, non-trivial files. Error whilst driving git?

**Comment by adityatoshniwal** [comment]
I had to rebuild the docs as I have changed internal values for lock layout levels. That is why it is showing so many file changes.

**Comment by adityatoshniwal** [comment]
Yes I noticed few garbage files here. I'll update the pull request.

**Comment by adityatoshniwal** [comment]
I have removed the garbage files and build the docs properly.

**Review by asheshv — APPROVED** [review]

**Pull request merged**
