### PR TITLE
Added option for rename panel

### PR DESCRIPTION
**Pull request by nikhil-mohite**
1. Added extra option for Rename panel.
2. Added extra check before the close panel to prevent closing non-closable panels.

### CODE REVIEW

**Comment by adityatoshniwal** [comment]
@nikhil-mohite just looking at the code it looks like you've used closeable flag to check if tab can be renamed.
I would say you add a new flag renamable because its not necessary that closable tab will be allowed to rename, eg-Dashboard.

**Comment by nikhil-mohite** [comment]
@adityatoshniwal as suggested added the new flag renamable, for the "Rename Panel" option.

**Review by adityatoshniwal — APPROVED** [review]
The code looks good to me.

**Review by asheshv — APPROVED** [review]

**Comment by asheshv** [comment]
Reviewed by Aditya, hence squashing the commits, and merging in the master repository.

**Pull request merged**
